services:
  - type: web
    name: vina
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: ""
        generateValue: false
      - key: JWT_SECRET
        value: ""
        generateValue: false
      - key: OAUTH_SERVER_URL
        value: ""
        generateValue: false
      - key: APP_URL
        value: ""
        generateValue: false

